[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 20
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001


[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://tasks.lb_osmosis:8000'
grpc_addr = 'http://tasks.lb_osmosis:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_osmosis:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 20000000
gas_price = { price = 0.003, denom = 'uosmo' }
gas_multiplier = 1.3
clock_drift = '100s'
trusting_period = '224hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    # sort by chain name
    ['transfer', 'channel-1'],   # akash
    ['transfer', 'channel-208'], # axelar-dojo-1
    ['transfer','channel-51'],   # bitcanna-1
    ['transfer', 'channel-113'], # chihuahua-1
    ['transfer','channel-72'],   # columbus-5
#    ['transfer', 'channel-87'],  # comdex-1
    ['transfer', 'channel-0'],   # cosmoshub
    ['transfer', 'channel-5'],   # crypto-org-chain-mainnet-1
    ['transfer', 'channel-171'], # konstellation (darchub)
    ['transfer', 'channel-144'], # gravity-bridge-3
    ['transfer', 'channel-6'],   # irishub-1
    ['transfer', 'channel-42'],  # juno
    ['transfer', 'channel-169'], # juno-1
    ['transfer', 'channel-143'], # kava_2222-10
    ['transfer', 'channel-77'],  # kichain-2
    ['transfer', 'channel-557'], # mars-1
    ['transfer', 'channel-199'], # omniflixhub-1
    ['transfer', 'channel-522'], # quicksilver-2
    ['transfer', 'channel-688'], # quasar-1
    ['transfer', 'channel-8'],   # regen-1
    ['transfer', 'channel-2'],   # sentinelhub-2
#    ['transfer', 'channel-47'],  # sifchain-1
    ['transfer', 'channel-75'],  # stargaze-1
    ['transfer', 'channel-326'], # stride-1
    ['transfer', 'channel-184'], # umee-1
#    ['transfer', 'channel-294'], # ????
]


[[chains]]
id = 'akashnet-2'
rpc_addr = 'http://tasks.lb_akash:8000'
grpc_addr = 'http://tasks.lb_akash:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_akash:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'akash'
key_name = 'akash'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'uakt' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-9']
]

[[chains]]
id = 'axelar-dojo-1'
rpc_timeout = '15s'
rpc_addr = 'http://tasks.lb_axelar:8000'
grpc_addr = 'http://tasks.lb_axelar:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_axelar:8000/websocket', batch_delay = '500ms' }
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 4000000
gas_price = { price = 0.0075, denom = 'uaxl' }
clock_drift = '50s'
trusting_period = '112hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-3'],
]


[[chains]]
id = 'bitcanna-1'
rpc_addr = 'http://tasks.lb_bitcanna:8000'
grpc_addr = 'http://tasks.lb_bitcanna:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_bitcanna:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'bcna'
key_name = 'bcna'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'ubcna' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '32hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-1'],
]

[[chains]]
id = 'chihuahua-1'
rpc_addr = 'http://tasks.lb_chihuahua:8000'
grpc_addr = 'http://tasks.lb_chihuahua:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_chihuahua:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'chihuahua'
key_name = 'chihuahua'
store_prefix = 'ibc'
max_tx_size = 1000000
default_gas = 100000000
max_gas = 1000000000
max_msg_num = 30
gas_price = { price = 0.1, denom = 'uhuahua' }
gas_multiplier = 2
clock_drift ='34s'
trusting_period = '224hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-7'],
]

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://tasks.lb_cosmoshub:8000'
grpc_addr = 'http://tasks.lb_cosmoshub:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_cosmoshub:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2500000
gas_price = { price = 0.01, denom = 'uatom' }
gas_multiplier = 2
clock_drift = '1000s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-141'],
]

[[chains]]
id = 'crypto-org-chain-mainnet-1'
rpc_addr = 'http://tasks.lb_cryptoorgchain:8000'
grpc_addr = 'http://tasks.lb_cryptoorgchain:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_cryptoorgchain:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'cro'
key_name = 'cro'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'basecro' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '448hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-10'],
]

[[chains]]
id = 'juno-1'
rpc_addr = 'http://tasks.lb_juno:8000'
grpc_addr = 'http://tasks.lb_juno:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_juno:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '50s'
account_prefix = 'juno'
key_name = 'juno'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2700000
gas_price = { price = 0.08, denom = 'ujuno' }
#gas_adjustment = 1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http://tasks.lb_gravitybridge:8000'
grpc_addr = 'http://tasks.lb_gravitybridge:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_gravitybridge:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'gravity'
key_name = 'gravity'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'ugraviton' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '32hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-10'],
]

[[chains]]
id = 'kava_2222-10'
rpc_addr = 'http://tasks.lb_kava:8000'
grpc_addr = 'http://tasks.lb_kava:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_kava:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'kava'
key_name = 'kava'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'ukava' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-1'],
]

[[chains]]
id = 'kichain-2'
rpc_addr = 'http://tasks.lb_kichain:8000'
grpc_addr = 'http://tasks.lb_kichain:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_kichain:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'ki'
key_name = 'ki'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'uxki' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-19'],
    ['transfer', 'channel-1'],
    ['transfer', 'channel-8'],
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'mars-1'
rpc_addr = 'http://tasks.lb_mars:8000'
grpc_addr = 'http://tasks.lb_mars:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_mars:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'mars'
key_name = 'mars'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'umars' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-1'],
]

[[chains]]
id = 'omniflixhub-1'
rpc_addr = 'http://tasks.lb_omniflixhub:8000'
grpc_addr = 'http://tasks.lb_omniflixhub:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_omniflixhub:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'omniflix'
key_name = 'omniflix'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'uflix' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-1'],
]

[[chains]]
id = 'quasar-1'
rpc_addr = 'http://tasks.lb_quasar:8000'
grpc_addr = 'http://tasks.lb_quasar:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_quasar:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'quasar'
key_name = 'quasar'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'uqsr' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-1'],
]

[[chains]]
id = 'quicksilver-2'
rpc_addr = 'http://tasks.lb_quicksilver:8000'
grpc_addr = 'http://tasks.lb_quicksilver:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_quicksilver:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '40s'
account_prefix = 'quick'
key_name = 'quick'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 180000
gas_price = { price = 0.0004, denom = 'uqck' }
#gas_multiplier = 2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-2'],
]

[[chains]]
id = 'regen-1'
rpc_addr = 'http://tasks.lb_regen:8000'
grpc_addr = 'http://tasks.lb_regen:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_regen:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '60s'
account_prefix = 'regen'
key_name = 'regen'
store_prefix = 'ibc'
max_tx_size = 100000
max_gas = 2000000
gas_price = { price = 0.007, denom = 'uregen' }
gas_multiplier = 1
clock_drift ='50s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-1'],
]

[[chains]]
id = 'sentinelhub-2'
rpc_addr = 'http://tasks.lb_sentinel:8000'
grpc_addr = 'http://tasks.lb_sentinel:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_sentinel:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'sent'
key_name = 'sentinel'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'udvpn' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-0'],
]

[[chains]]
id = 'stargaze-1'
rpc_addr = 'http://tasks.lb_stargaze:8000'
grpc_addr = 'http://tasks.lb_stargaze:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_stargaze:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'stars'
key_name = 'stars'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas = 1000000
gas_price = { price = 1, denom = 'ustars' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1000000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '224hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'stride-1'
rpc_addr = 'http://tasks.lb_stride:8000'
grpc_addr = 'http://tasks.lb_stride:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_stride:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'stride'
key_name = 'stride'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'ustrd' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '224hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-9'],
    ['transfer', 'channel-5'],
    ['transfer', 'channel-24'],
    ['transfer', 'channel-19'],
    ['transfer', 'channel-49'],
    ['transfer', 'channel-29'],
    ['transfer', 'channel-51'],
]


[[chains]]
id = 'umee-1'
rpc_addr = 'http://tasks.lb_umee:8000'
grpc_addr = 'http://tasks.lb_umee:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_umee:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'umee'
key_name = 'umee'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.1, denom = 'uumee' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '224hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]
