[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 20
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'migaloo-1'
rpc_addr = 'http://tasks.lb_whitewhale:8000'
grpc_addr = 'http://tasks.lb_whitewhale:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_whitewhale:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'migaloo'
key_name = 'migaloo'
store_prefix = 'ibc'
max_gas = 5000000
max_msg_num = 30
max_tx_size = 3000000
gas_price = { price = 0.4, denom = 'uwhale' }
gas_multiplier = 2
clock_drift = '500s'
trusting_period = '336hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-10'],
    ['transfer', 'channel-27'],
    ['transfer', 'channel-22'],
    ['transfer', 'channel-48'],
    ['transfer', 'channel-49'],
    ['transfer', 'channel-28'],
    ['transfer', 'channel-53'],
    ['transfer', 'channel-9']
]

[[chains]]
id = 'chihuahua-1'
rpc_addr = 'http://tasks.lb_chihuahua:8000'
grpc_addr = 'http://tasks.lb_chihuahua:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_chihuahua:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'chihuahua'
key_name = 'chihuahua'
store_prefix = 'ibc'
max_tx_size = 1000000
default_gas = 100000000
max_gas = 1000000000
max_msg_num = 30
gas_price = { price = 0.1, denom = 'uhuahua' }
gas_multiplier = 2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-39'],
]

[[chains]]
id = 'neutron-1'
rpc_addr = 'http://tasks.lb_neutron:8000'
grpc_addr = 'http://tasks.lb_neutron:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_neutron:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'neutron'
key_name = 'neutron'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas = 1000000
gas_price = { price = 0.6, denom = 'untrn' }
gas_multiplier = 1.2
max_msg_num = 20
#ccv_consumer_chain = true
max_tx_size = 2097152
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '13days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-57'],
]

[[chains]]
id = 'umee-1'
rpc_addr = 'http://tasks.lb_umee:8000'
grpc_addr = 'http://tasks.lb_umee:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_umee:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'umee'
key_name = 'umee'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.1, denom = 'uumee' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '216hours'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-57'],
]

[[chains]]
id = 'kava_2222-10'
rpc_addr = 'http://tasks.lb_kava:8000'
grpc_addr = 'http://tasks.lb_kava:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_kava:8000/websocket', batch_delay = '500ms' }
rpc_timeout = '20s'
account_prefix = 'kava'
key_name = 'kava'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 300000
max_gas =  10000000
gas_price = { price = 0.0025, denom = 'ukava' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '40s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-120'],
]

[[chains]]
id = 'axelar-dojo-1'
rpc_timeout = '15s'
rpc_addr = 'http://tasks.lb_axelar:8000'
grpc_addr = 'http://tasks.lb_axelar:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_axelar:8000/websocket', batch_delay = '500ms' }
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 4000000
gas_price = { price = 0.0075, denom = 'uaxl' }
clock_drift = '50s'
trusting_period = '112hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-112'],
    ['transfer', 'channel-92'],
    ['transfer', 'channel-121'],
    ['transfer', 'channel-66']
]