{
 "title": "MyDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rpc",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv0'}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "Api",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv1'}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "Grpc",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv3'}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "Webservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv2'}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  }
 ]
}