{
 "title": "MyDashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Rpc",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv0'}[5m]) or rate(haproxy_frontend_http_requests_total{proxy=\"fe_rpc\"}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "Rpc Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket[5m]) or rate(haproxy_backend_response_time_average_seconds{proxy=\"be_rpc\"}[5m]) ))"
    }
   ]
  },
  {
   "title": "Grpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv3'}[5m]) or rate(haproxy_frontend_http_requests_total{proxy=\"fe_grpc\"}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "Api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv1'}[5m]) or rate(haproxy_frontend_http_requests_total{proxy=\"fe_api\"}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "Webservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv2'}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  },
  {
   "title": "JSONRPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server='srv4'}[5m]) or rate(haproxy_frontend_http_requests_total{proxy=\"fe_eth\"}[5m])",
     "legendFormat": "{{instance}}_{{server}}"
    }
   ]
  }
 ]
}