global:
  scrape_interval: 60s # default is 1 minute

scrape_configs:
  - job_name: lb_cosmoshub
    static_configs:
      - targets: ['tasks.lb_cosmoshub:2019']
  - job_name: lb_juno
    static_configs:
      - targets: ['tasks.lb_juno:2019']
  - job_name: lb_osmosis
    static_configs:
      - targets: ['tasks.lb_osmosis:2019']
  - job_name: lb_starname
    static_configs:
      - targets: ['tasks.lb_starname:2019']
  - job_name: lb_regen
    static_configs:
      - targets: ['tasks.lb_regen:2019']
  - job_name: lb_akash
    static_configs:
      - targets: ['tasks.lb_akash:2019']
  - job_name: lb_sentinel
    static_configs:
      - targets: ['tasks.lb_sentinel:2019']
  - job_name: lb_emoney
    static_configs:
      - targets: ['tasks.lb_emoney:2019']
  - job_name: lb_terra
    static_configs:
      - targets: ['tasks.lb_terra:2019']
  - job_name: lb_ixo
    static_configs:
      - targets: ['tasks.lb_ixo:2019']
  - job_name: lb_sifchain
    static_configs:
      - targets: ['tasks.lb_sifchain:2019']
  - job_name: lb_likecoin
    static_configs:
      - targets: ['tasks.lb_likecoin:2019']
  - job_name: lb_kichain
    static_configs:
      - targets: ['tasks.lb_kichain:2019']
  - job_name: lb_cyber
    static_configs:
      - targets: ['tasks.lb_cyber:2019']
  - job_name: lb_cheqd
    static_configs:
      - targets: ['tasks.lb_cheqd:2019']
  - job_name: lb_stargaze
    static_configs:
      - targets: ['tasks.lb_stargaze:2019']
  - job_name: lb_bandchain
    static_configs:
      - targets: ['tasks.lb_bandchain:2019']
  - job_name: lb_chihuahua
    static_configs:
      - targets: ['tasks.lb_chihuahua:2019']
  - job_name: lb_kava
    static_configs:
      - targets: ['tasks.lb_kava:2019']
  - job_name: lb_bitcanna
    static_configs:
      - targets: ['tasks.lb_bitcanna:2019']
  - job_name: lb_konstellation
    static_configs:
      - targets: ['tasks.lb_konstellation:2019']
  - job_name: lb_omniflixhub
    static_configs:
      - targets: ['tasks.lb_omniflixhub:2019']
  - job_name: lb_vidulum
    static_configs:
      - targets: ['tasks.lb_vidulum:2019']
  - job_name: lb_provenance
    static_configs:
      - targets: ['tasks.lb_provenance:2019']
  - job_name: lb_dig
    static_configs:
      - targets: ['tasks.lb_dig:2019']
  - job_name: lb_gravitybridge
    static_configs:
      - targets: ['tasks.lb_gravitybridge:2019']
  - job_name: lb_bitsong
    static_configs:
      - targets: ['tasks.lb_bitsong:2019']
  - job_name: lb_assetmantle
    static_configs:
      - targets: ['tasks.lb_assetmantle:2019']
  - job_name: lb_fetchhub
    static_configs:
      - targets: ['tasks.lb_fetchhub:2019']
  - job_name: lb_evmos
    static_configs:
      - targets: ['tasks.lb_evmos:2019']
  - job_name: lb_persistent
    static_configs:
      - targets: ['tasks.lb_persistent:2019']
  - job_name: lb_cryptoorgchain
    static_configs:
      - targets: ['tasks.lb_cryptoorgchain:2019']
  - job_name: lb_irisnet
    static_configs:
      - targets: ['tasks.lb_irisnet:2019']
  - job_name: lb_axelar
    static_configs:
      - targets: ['tasks.lb_axelar:2019']
  - job_name: lb_umee
    static_configs:
      - targets: ['tasks.lb_umee:2019']
  - job_name: lb_sei
    static_configs:
      - targets: ['tasks.lb_sei:2019']
  - job_name: lb_injective
    static_configs:
      - targets: ['tasks.lb_injective:2019']
  - job_name: lb_kujira
    static_configs:
      - targets: ['tasks.lb_kujira:2019']
  - job_name: lb_passage
    static_configs:
      - targets: ['tasks.lb_passage:2019']
  - job_name: lb_osmosis-testnet
    static_configs:
      - targets: ['tasks.lb_osmosis-testnet:2019']
  - job_name: lb_stride
    static_configs:
      - targets: ['tasks.lb_stride:2019']
  - job_name: lb_dig-archive
    static_configs:
      - targets: ['tasks.lb_dig-archive:2019']
  - job_name: lb_quicksilver
    static_configs:
      - targets: ['tasks.lb_quicksilver:2019']
  - job_name: lb_juno-archive-sub
    static_configs:
      - targets: ['tasks.lb_juno-archive-sub:2019']
  - job_name: lb_terra2
    static_configs:
      - targets: ['tasks.lb_terra2:2019']
  - job_name: lb_osmosis-archive-sub1
    static_configs:
      - targets: ['tasks.lb_osmosis-archive-sub1:2019']
  - job_name: lb_mars
    static_configs:
      - targets: ['tasks.lb_mars:2019']
  - job_name: lb_whitewhale-testnet
    static_configs:
      - targets: ['tasks.lb_whitewhale-testnet:2019']
  - job_name: lb_noble
    static_configs:
      - targets: ['tasks.lb_noble:2019']
  - job_name: lb_whitewhale
    static_configs:
      - targets: ['tasks.lb_whitewhale:2019']
  - job_name: lb_quasar
    static_configs:
      - targets: ['tasks.lb_quasar:2019']
  - job_name: lb_osmosis-archive-sub
    static_configs:
      - targets: ['tasks.lb_osmosis-archive-sub:2019']
  - job_name: lb_celestia-testnet
    static_configs:
      - targets: ['tasks.lb_celestia-testnet:2019']
  - job_name: lb_juno-archive-sub1
    static_configs:
      - targets: ['tasks.lb_juno-archive-sub1:2019']
  - job_name: lb_juno-archive-sub2
    static_configs:
      - targets: ['tasks.lb_juno-archive-sub2:2019']
  - job_name: lb_sei-testnet
    static_configs:
      - targets: ['tasks.lb_sei-testnet:2019']
  - job_name: lb_cosmoshub-archive-sub1
    static_configs:
      - targets: ['tasks.lb_cosmoshub-archive-sub1:2019']
  - job_name: lb_cosmoshub-archive-sub
    static_configs:
      - targets: ['tasks.lb_cosmoshub-archive-sub:2019']