{
 "title": "MyDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Composable", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Client Update [composable]",
   "type": "table",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/composable_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [composable]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"composable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coreum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Last Client Update [coreum]",
   "type": "table",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/coreum_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [coreum]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 31 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"coreum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Furya", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Last Client Update [furya]",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/furya_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [furya]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 58 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"furya\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Injective", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Last Client Update [osmosis]",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/injective_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [injective]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"injective\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kava", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Last Client Update [kava]",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/kava_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [kava]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 80 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"kava\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Osmosis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Last Client Update [osmosis]",
   "type": "table",
   "gridPos": { "h": 34, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/osmosis_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [osmosis]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 34, "w": 12, "x": 12, "y": 98 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"osmosis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sei", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Last Client Update [sei]",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/sei_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [sei]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 133 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"sei\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Last Client Update [test]",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 146 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/test_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [test]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 146 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"test\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallet Balances - Cron [test]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 146 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"test_clear\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Whitewhale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Last Client Update [whitewhale]",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 153 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].chain_id" },
      { "jsonPath": "$.[*].channel_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].counter_chain_id", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].pending_packets", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.[*].time_ago", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "hermes_config_url",
       "https://raw.githubusercontent.com/notional-labs/cosmosia/main/relaying/whitewhale_config.toml"
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances [whitewhale]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 153 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"whitewhale\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallet Balances - Cron [whitewhale]",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 153 },
   "options": {
    "content": "<table>\n  <tr>\n    <th>account</th>\n    <th>balance</th>\n  </tr>\n  {{#each data}}\n  <tr>\n    <td>\n      <font size=\"+1\">{{account}}</font><br>\n      chain: {{chain}}, relayer-hub: {{job}}\n    </td>\n    <td>\n      <font size=\"+2\">{{Value}}</font> \n      {{denom}}\n    </td>\n  </tr>\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "expr": "wallet_balance{job=\"whitewhale_clear\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}