${INC_GLOBAL}

[[chains]]
id = 'osmosis-1'
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = 'allow'
list = [
    # sort by chain chain_id
    ['transfer', 'channel-1'],   # akashnet-2
    ['transfer', 'channel-208'], # axelar-dojo-1
    ['transfer','channel-51'],   # bitcanna-1
    ['transfer', 'channel-113'], # chihuahua-1
#    ['transfer','channel-72'],   # columbus-5 (channel-1), moved to stuck
    ['transfer', 'channel-0'],   # cosmoshub
    ['transfer', 'channel-5'],   # crypto-org-chain-mainnet-1
    ['transfer', 'channel-171'], # darchub (konstellation)
    ['transfer', 'channel-144'], # gravity-bridge-3
    ['transfer', 'channel-6'],   # irishub-1
    ['transfer', 'channel-42'],  # juno
    ['transfer', 'channel-169'], # juno-1
    ['transfer', 'channel-77'],  # kichain-2
#    ['transfer', 'channel-557'], # mars-1 (channel-1), moved to stuck
    ['transfer', 'channel-199'], # omniflixhub-1
    ['transfer', 'channel-783'], # pirin-1 (nolus)
    ['transfer', 'channel-522'], # quicksilver-2
    ['transfer', 'channel-688'], # quasar-1
    ['transfer', 'channel-8'],   # regen-1
    ['transfer', 'channel-2'],   # sentinelhub-2
    ['transfer', 'channel-75'],  # stargaze-1
    ['transfer', 'channel-326'], # stride-1
    ['transfer', 'channel-184'], # umee-1
]

[[chains]]
id = 'akashnet-2'
${INC_AKASHNET_2}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-9']
]

[[chains]]
id = 'axelar-dojo-1'
${INC_AXELAR_DOJO_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-3'],
]

[[chains]]
id = 'bitcanna-1'
${INC_BITCANNA_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-1'],
]

[[chains]]
id = 'chihuahua-1'
${INC_CHIHUAHUA_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-7'],
]

[[chains]]
id = 'cosmoshub-4'
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-141'],
]

[[chains]]
id = 'crypto-org-chain-mainnet-1'
${INC_CRYPTO_ORG_CHAIN_MAINNET_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-10'],
]

[[chains]]
id = 'darchub'
${INC_DARCHHB}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'juno-1'
${INC_JUNO_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'gravity-bridge-3'
${INC_GRAVITY_BRIDGE_3}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-10'],
]

[[chains]]
id = 'irishub-1'
${INC_IRISHUB_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-3'],
]


[[chains]]
id = 'kichain-2'
${INC_KICHAIN_2}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'omniflixhub-1'
${INC_OMNIFLIXHUB_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-1'],
]

[[chains]]
id = 'pirin-1'
${INC_PIRIN_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'quasar-1'
${INC_QUASAR_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-1'],
]

[[chains]]
id = 'quicksilver-2'
${INC_QUICKSILVER_2}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-2'],
]

[[chains]]
id = 'regen-1'
${INC_REGEN_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-1'],
]

[[chains]]
id = 'sentinelhub-2'
${INC_SENTINELHUB_2}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'stargaze-1'
${INC_STARGAZE_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = 'stride-1'
${INC_STRIDE_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-5'],
]


[[chains]]
id = 'umee-1'
${INC_UMEE_1}
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]
