${INC_GLOBAL}

[[chains]]
id = "quicksilver-2"
${INC_QUICKSILVER_2}
[chains.packet_filter]
policy = "allow"
list = [
      ['transfer', 'channel-0'], ## stargaze
      ['transfer', 'channel-1'], ## cosmos
      ['transfer', 'channel-2'], ## osmosis
      ['transfer', 'channel-17'], ## regen
      #['transfer','channel-52'], ##secret
      ['transfer','channel-86'], #juno
      ['transfer','channel-101'], #somm (expired)
      ['transfer','channel-164'], #dydx
      ['transfer','channel-170'], #saga (expired)
      ['transfer','channel-171'], #arch
#      ['icacontroller-*', '*']
      ['icacontroller-cosmoshub-4.deposit','channel-12'], # cosmos
      ['icacontroller-cosmoshub-4.withdrawal','channel-13'], # cosmos
      ['icacontroller-cosmoshub-4.performance','channel-194'], # cosmos
      ['icacontroller-cosmoshub-4.delegate','channel-193'], # cosmos
      ['icacontroller-dydx-mainnet-1.deposit','channel-165'], # dydx
      ['icacontroller-dydx-mainnet-1.withdrawal','channel-166'], # dydx
      ['icacontroller-dydx-mainnet-1.performance','channel-167'], # dydx
      ['icacontroller-dydx-mainnet-1.delegate','channel-168'], # dydx
      ['icacontroller-agoric-3.deposit','channel-177'], # agoric
      ['icacontroller-agoric-3.withdrawal','channel-178'], # agoric
      ['icacontroller-agoric-3.performance','channel-179'], # agoric
      ['icacontroller-agoric-3.delegate','channel-180'], # agoric
#      ['icacontroller-ssc-1.deposit','channel-173'], # saga (expired)
#      ['icacontroller-ssc-1.withdrawal','channel-174'], # saga (expired)
#      ['icacontroller-ssc-1.performance','channel-175'], # saga (expired)
#      ['icacontroller-ssc-1.delegate','channel-176'], # saga (expired)
      ['icacontroller-osmosis-1.deposit','channel-25'], # osmosis
      ['icacontroller-osmosis-1.withdrawal','channel-26'], # osmosis
      ['icacontroller-osmosis-1.performance','channel-27'], # osmosis
      ['icacontroller-osmosis-1.delegate','channel-160'], # osmosis
#      ['icacontroller-sommelier-3.deposit','channel-103'], # sommelier (expired)
#      ['icacontroller-sommelier-3.withdrawal','channel-104'], # sommelier (expired)
#      ['icacontroller-sommelier-3.performance','channel-105'], # sommelier (expired)
#      ['icacontroller-sommelier-3.delegate','channel-120'], # sommelier (expired)
      ['icacontroller-stargaze-1.deposit','channel-3'], # stargaze
      ['icacontroller-stargaze-1.withdrawal','channel-4'], # stargaze
      ['icacontroller-stargaze-1.performance','channel-5'], # stargaze
      ['icacontroller-stargaze-1.delegate','channel-181'], # stargaze
      ['icacontroller-juno-1.deposit','channel-90'], # juno
      ['icacontroller-juno-1.withdrawal','channel-91'], # juno
      ['icacontroller-juno-1.performance','channel-191'], # juno
      ['icacontroller-juno-1.delegate','channel-195'], # juno
      ['icacontroller-regen-1.deposit','channel-18'], # regen
      ['icacontroller-regen-1.withdrawal','channel-19'], # regen
      ['icacontroller-regen-1.performance','channel-190'], # regen
      ['icacontroller-regen-1.delegate','channel-189'], # regen
]

[[chains]]
id = "cosmoshub-4"
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = "allow"
list = [
      ['transfer', 'channel-467'],
      ['icahost', 'channel-529'],
      ['icahost', 'channel-531'],
      ['icahost', 'channel-530'],
      ['icahost', 'channel-832'],
]

[[chains]]
id = "juno-1"
${INC_JUNO_1}
[chains.packet_filter]
policy = "allow"
list = [
      ['transfer', 'channel-272'],
      ['icahost', 'channel-531'],
      ['icahost', 'channel-277'], ## deposit
      ['icahost', 'channel-274'], ## withdrawal
      ['icahost', 'channel-482'], ## perform
]

[[chains]]
id = "osmosis-1"
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = "allow"
list = [
      ['transfer', 'channel-522'],
      ['icahost', 'channel-701'], ## deposit
      ['icahost', 'channel-698'], ## withdrawal
      ['icahost', 'channel-700'], ## performance
      ['icahost', 'channel-17604'],
]

[[chains]]
id = 'regen-1'
${INC_REGEN_1}
[chains.packet_filter]
policy = 'allow'
list = [
      ['transfer', 'channel-62'],
      ['icahost', 'channel-163'], ## delegate
      ['icahost', 'channel-65'], ## deposit
      ['icahost', 'channel-63'], ## withdrawal
      ['icahost', 'channel-64'], ## performance
]

[[chains]]
id = 'sommelier-3'
${INC_SOMMELIER_3}
[chains.packet_filter]
policy = 'allow'
list = [
#        ['transfer', 'channel-59'], # (expired)
#        ['icahost', 'channel-78'], ## delegate (expired)
#        ['icahost', 'channel-60'], ## deposit (expired)
#        ['icahost', 'channel-61'], ## withdrawal (expired)
#        ['icahost', 'channel-62'], ## performance (expired)
]

[[chains]]
id = 'stargaze-1'
${INC_STARGAZE_1}
[chains.packet_filter]
policy = 'allow'
list = [
      ['transfer', 'channel-124'],
      ['icahost', 'channel-196'], ## delegate
      ['icahost', 'channel-126'], ## deposit
      ['icahost', 'channel-129'], ## withdrawal
      ['icahost', 'channel-130'], ## performance
]

[[chains]]
id = "dydx-mainnet-1"
${INC_DYDX_MAINNET_1}
[chains.packet_filter]
policy = "allow"
list = [
      ['transfer', 'channel-32'],
      ['icahost', 'channel-35'], ## delegate
      ['icahost', 'channel-33'], ## deposit
      ['icahost', 'channel-34'], ## withdrawal
      ['icahost', 'channel-36'], ## performance
]

[[chains]]
id = "ssc-1"
${INC_SSC_1}
[chains.packet_filter]
policy = "allow"
list = [
#      ['transfer', 'channel-18'], # (expired)
#      ['icahost', 'channel-19'], ## delegate (expired)
#      ['icahost', 'channel-22'], ## deposit (expired)
#      ['icahost', 'channel-20'], ## withdrawal (expired)
#      ['icahost', 'channel-21'], ## performance (expired)
]

[[chains]]
id = "archway-1"
${INC_ARCHWAY_1}
[chains.packet_filter]
policy = "allow"
list = [
      ['transfer', 'channel-132'],
#      ['icahost', 'channel-19'], ## delegate
#      ['icahost', 'channel-22'], ## deposit
#      ['icahost', 'channel-20'], ## withdrawal
#      ['icahost', 'channel-21'], ## performance
]

[[chains]]
id = "agoric-3"
${INC_AGORIC_3}
[chains.packet_filter]
policy = "allow"
list = [
#      ['transfer', 'channel-18'],
#      ['icahost', 'channel-19'], ## delegate
#      ['icahost', 'channel-22'], ## deposit
#      ['icahost', 'channel-20'], ## withdrawal
#      ['icahost', 'channel-21'], ## performance
]