[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 0
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = "migaloo-1"
${INC_MIGALOO_1}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain_id
    ['transfer', 'channel-49'], # axelar-dojo-1
    ['transfer', 'channel-53'], # axelar-dojo-1
    ['transfer', 'channel-10'], # chihuahua-1
#    ['transfer', 'channel-27'], # neutron-1
    ['transfer', 'channel-48'], # kava_2222-10
    ['transfer', 'channel-69'], # stargaze-1
    ['transfer', 'channel-56'], # umee-1
]

[[chains]]
id = "axelar-dojo-1"
${INC_AXELAR_DOJO_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-112'],
    ['transfer', 'channel-121'],
]

[[chains]]
id = "chihuahua-1"
${INC_CHIHUAHUA_1}

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-39'],
]

[[chains]]
id = "neutron-1"
${INC_NEUTRON_1}
[chains.packet_filter]
policy = "allow"
list = [
#    ['transfer', 'channel-4'],
]

[[chains]]
id = "kava_2222-10"
${INC_KAVA_2222_10}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-120'],
]

[[chains]]
id = "stargaze-1"
${INC_STARGAZE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-269'],
]

[[chains]]
id = "umee-1"
${INC_UMEE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-104'],
]
