${INC_GLOBAL}

[[chains]]
id = "narwhal-2"
${INC_NARWHAL_2}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain_id
#    ['transfer', 'channel-1'], # osmo-test-5
#    ['transfer', 'channel-2'], # theta-testnet-001
]

[chains.packet_filter.min_fees]

[[chains]]
id = "osmo-test-5"
${INC_OSMO_TEST_1}
[chains.packet_filter]
policy = "allow"
list = [
#    ['transfer', 'channel-1'],
]

[[chains]]
id = "theta-testnet-001"
${INC_THETA_TESTNET_001}
[chains.packet_filter]
policy = "allow"
list = [
#    ['transfer', 'channel-1'],
]
